Repository project-chip/certification-tool-backend, pull requests merged in 2025-05, with the labels that each got.

#217 Fix 1.5_in_progress missing folder
  test_collections/matter/sdk_tests/scripts/fetch_sdk_tests_and_runner.sh
  test_collections/matter/sdk_tests/support/sdk_container.py
Labels: v1.5

#218 Added logs for applicable test cases
  app/pics_applicable_test_cases.py
Labels: v1.5

#219 [FIX] Adding Step Manual Missing Parameter
  test_collections/matter/sdk_tests/support/yaml_tests/models/chip_test.py
Labels: bug

#220 Fixed some platform tests not being added to applicable test cases
  app/pics_applicable_test_cases.py
Labels: v1.5

#224 Changes for v2.13-beta4+summer2025 version
  .version_information
  cspell.json
  test_collections/matter/config.py
Labels: v1.4.2
